#' Highest level wrapper function for Gap-filling and z-normalizing the data
#' @description This function gap-fills and z-normalizes the metabolism and
#' associated driver data.
#'
#' @param synthesis_filtered The filtered dataset generated by the filter_metab function
#' 
#' @param PQ the photosynthetic quotient used to convert aquatic metabolism estimates 
#' to gC m-1 d-1
#' 
#' @param block The size of the largest block of missing data that the function will fill-in. 
#' Parameter for fillMiss3.R
#' 
#' @param pmiss The maximum amount of the missing data that can be missing in the 
#' dataset for fill-in procedure to be performed. Parameter for fillMiss3.R
#' 
#' @return Returns gap-filled and z-normalized time series
#'
#' @export
#===============================================================================
#Define the highest level wrapper function for gap-filling
#===============================================================================
  synthesis_gapfill <- function(synthesis_filtered, PQ, block, pmiss){
    #Wrapper function to gap-fill each year of data individually
      site_gapfill <- function(SOI, PQ){
        # #Get data for the site of interest
        #   SOI <- synthesis_filtered[[Site_ID]]        
        
        #Split by year
          year_split <- split(SOI, SOI[, "Year"])
      
        #Gap-fill and z-normalize data for each year
        #Aquatic metabolism is also converted to C
          filled <- do.call(rbind, lapply(year_split, FUN = gapfill_norm, PQ = PQ, 
            block = block, pmiss = pmiss)) 
          
        return(filled)  
      } #End year_gapfill function
      
    #Apply the function over each site
      gapfilled_data <- lapply(synthesis_filtered, FUN = site_gapfill, PQ = PQ) 
      
    return(gapfilled_data)
      
  } #End synthesis_gapfill function